# This is a basic workflow to help you get started with Actions

name: NiceBlog

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ blog ]
  pull_request:
    branches: [ blog ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GH_USENAME: niceRAM
  GH_EMAIL: niceniceram@gmail.com
  GH_REPO: niceRAM/niceram.github.io
  GH_BRANCH: master
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: blog
          submodules: true

      - name: Hugo Build
        uses: jakejarvis/hugo-build-action@v0.81.0
        with:
          args: --minify

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: alpine/git
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: site
    - name: Setup git
      run: |
        git config --global user.name "${GH_USERNAME}"
        git config --global user.email "${GH_EMAIL}"
    - name: Deploy to GitHub
      run: |
        git init && git add .
        for try in $(seq 10); do
          git commit -m "Build By GitHub Actions on $(date "+%Y-%m-%d %T")"
          if git push -f "https://${{ secrets.DEPLOY_TOKEN }}@github.com/${GH_REPO}" master:${GH_BRANCH}; then
            exit 0
          else
            sleep $(shuf -i 3-10 -n 1)
          fi
        done
        exit 1
